### ISSUE TITLE
Why does this use JQuery?

### ISSUE THREAD

**Issue by mistermantas** [mishterk/wp-tailwindcss-theme-boilerplate#33]
It seems so antiquated compared to Tailwind, plus this is a boilerplate

**Comment by mishterk** [comment]
jQuery ships with WordPress and it's the standard and most commonly used library used when building WordPress. As soon as you add plugins, they'll more than likely enqueue jQuery so it makes sense to use it instead of stacking on other libraries. 

If you don't want to use it, you don't have to. Deregister and replace with whatever you prefer. It's a boilerplate, so do whatever you must to suit your needs. The JS utilities that are included are just bonuses that I put in there because I use them often.

**Comment by mistermantas** [comment]
thank you for the explanation! ♥️
